theme: jekyll-theme-minimal

# Site wide configuration

title: Nuno Dâmaso @ Do iT Lean
locale: en_US
logo: images/logo.svg

# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name: Nuno Dâmaso
  avatar: images/bio-photo.jpg
  bio: ""
  email: nuno.damaso@doitlean.com
  # Do not include the @ symbol in your Twitter username
  twitter: NunoDamaso
  linkedin: https://www.linkedin.com/in/nunosdamaso/
  github: nunodamaso-dil
